// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR1klsp8TetdxgLP1_QHkTIhIhiw2We94',
    appId: '1:1031696610807:web:41861b9b793daad7ed6af2',
    messagingSenderId: '1031696610807',
    projectId: 'studycards-e3d50',
    authDomain: 'studycards-e3d50.firebaseapp.com',
    storageBucket: 'studycards-e3d50.appspot.com',
    measurementId: 'G-PWZVTSX78P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo5mkg2BeoIStG2fO07wJ5gO55ctIPhgc',
    appId: '1:1031696610807:android:3cd8956d5419b347ed6af2',
    messagingSenderId: '1031696610807',
    projectId: 'studycards-e3d50',
    storageBucket: 'studycards-e3d50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpauHlhYl7YlPr0g8m0paHzb6yWZeM_-0',
    appId: '1:1031696610807:ios:f5d1645adc0df661ed6af2',
    messagingSenderId: '1031696610807',
    projectId: 'studycards-e3d50',
    storageBucket: 'studycards-e3d50.appspot.com',
    iosClientId: '1031696610807-h56h8hc3u44jc02ikta7neshkjbcq35p.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyCards',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpauHlhYl7YlPr0g8m0paHzb6yWZeM_-0',
    appId: '1:1031696610807:ios:47cfb8b05d15c917ed6af2',
    messagingSenderId: '1031696610807',
    projectId: 'studycards-e3d50',
    storageBucket: 'studycards-e3d50.appspot.com',
    iosClientId: '1031696610807-gbb9cibdrgje3650sdnncoumvu0umlhq.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyCards.RunnerTests',
  );
}
