name: study_cards
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_sound: ^9.2.13
  scribble: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
