name: study_cards
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <4.0.0'

dependencies:
  firebase_core: ^2.9.0
  fluent_ui: ^4.4.0
  flutter:
    sdk: flutter
  flutter_spinbox: ^0.12.0
  image: ^4.0.15
  image_picker: ^0.8.6+2
  path: ^1.8.2
  path_provider: ^2.0.12
  scribble: ^0.9.1
  cloud_firestore:
  firebase_storage:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
